import Head from "next/head";
import { Fragment } from "react";
import { useRouter } from "next/router";
import UserDetails from "@/components/user-details/UserDetails";

export default function DetailsPage() {
  const router = useRouter();
  const id = router.query.id;

  if (!id) {
    return <div>Loading...</div>;
  }

  return (
    <Fragment>
      <Head>
        <title>User Management App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserDetails id={id.toString()} />
    </Fragment>
  );
}
